ReconWeb/Controllers/CommonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Razor.TagHelpers;
using NuGet.Common;
using System.Net.Http;
using Newtonsoft.Json;
using System.Security.Policy;

namespace Recon.Controllers
{
    public class CommonController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ILogger<CommonController> _logger;
        private readonly HttpClient _httpClient;

        public CommonController(
            IConfiguration configuration,
            IHttpClientFactory httpClientFactory,
            ILogger<CommonController> logger)
        {
            _configuration = configuration;
            _httpClientFactory = httpClientFactory;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        //public string GetApiResult(string serializedString, string apiMethodName)
        //{
        //    string post_data = "";
        //    try
        //    {

        //        using (var client = new HttpClient())
        //        {
        //            client.BaseAddress = new Uri("https://localhost:44348/api/UserManagement/");
        //            client.DefaultRequestHeaders.Accept.Clear();
        //            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        //            HttpContent content = new StringContent(serializedString, UTF8Encoding.UTF8, "application/json");
        //            content.Headers.Add("user_code", "12345");
        //            var response = client.PostAsync("Loginvalidation", content).Result;
        //            if (response.StatusCode.ToString() == "Unauthorized")
        //            {
        //                Console.WriteLine("Inside If");
        //            }
        //            else
        //            {
        //                Stream data = response.Content.ReadAsStreamAsync().Result;
        //                StreamReader reader = new StreamReader(data);
        //                post_data = reader.ReadToEnd();
        //            }

        //        }

        //    }
        //    catch (Exception ex)
        //    {
        //        if (ex.Message == "Object reference not set to an instance of an object.")
        //        {
        //            Console.WriteLine("Inside If");
        //        }
        //        else
        //        {
        //            string control = this.ControllerContext.RouteData.Values["controller"].ToString(); 
        //            //LogHelper.WriteLog(ex.ToString(), control);
        //        }
        //    }
        //    return post_data;
        //}


        //Hema


        [HttpGet]
        public async Task GetToken()
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var form = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("grant_type", "password"),
                    new KeyValuePair<string, string>("username", "user"),
                    new KeyValuePair<string, string>("password", "user"),
                });

                var tokenResponse = await client.PostAsync(_configuration["URL"] + "/token", form);

                if (tokenResponse.IsSuccessStatusCode)
                {
                    var token = await tokenResponse.Content.ReadFromJsonAsync<Token>();
                    string tokenValue = token.access_token;
                    HttpContext.Session.SetString("token_", tokenValue);
                }
            }
            catch (Exception ex)
            {
                string control = this.ControllerContext.RouteData.Values["controller"].ToString();
                //LogHelper.WriteLog(ex.ToString(), control);
                _logger.LogError(ex.ToString(), control);

            }
        }


        public string GetApiResult(string serializedString, string apiMethodName)
        {
            string post_data = "";
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:4195/api/UserManagement/");
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpContent content = new StringContent(serializedString, UTF8Encoding.UTF8, "application/json");
                    // content.Headers.Add("user_code", "12345"); // Remove if not needed
                    var response = client.PostAsync("Loginvalidation", content).Result;

                    // Check for a successful response (HTTP 200 OK)
                    if (response.IsSuccessStatusCode)
                    {
                        Stream data = response.Content.ReadAsStreamAsync().Result;
                        StreamReader reader = new StreamReader(data);
                        post_data = reader.ReadToEnd();
                    }
                    else
                    {
                        // Log the full response for debugging
                        Console.WriteLine($"API call failed with status code: {response.StatusCode}");
                        Console.WriteLine(response.Content.ReadAsStringAsync().Result);
                    }
                }
            }
            catch (Exception ex)
            {
                string control = this.ControllerContext.RouteData.Values["controller"].ToString();
                // Log the exception for debugging
                Console.WriteLine($"Exception: {ex.Message}");
                // LogHelper.WriteLog(ex.ToString(), control);
            }
            return post_data;
        }



        public class Token
        {
            public string? access_token { get; set; }
        }

    }
}

ReconWeb/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using ReconWeb.Models;
using System.Net;
using System.Text;
using Newtonsoft.Json;
using System.Security.Cryptography;
using System.Net.Mail;
using Recon_Model;
using static Recon.Controllers.LoginController;
using System.Net.Http.Headers;
using static Recon_Model.user_model;

namespace Recon.Controllers
{
    public class LoginController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<LoginController> _logger;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly CommonController _commonController;
        string ipAddress = "";

        public LoginController(
            CommonController commonController,
            IConfiguration configuration,
            ILogger<LoginController> logger,
            IHttpContextAccessor httpContextAccessor)
        {
            _commonController = commonController;
            _configuration = configuration;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Login()
        {
            return View();
        }
        public class Login_model1
        {
            public string? UserName { get; set; }
            public string? Password { get; set; }
        }


        [HttpPost]
       public string Login_validation([FromBody] Login_model1 model)
        {
            string post_data = "";
            DataTable result = new DataTable();
            List<user_model> objcat_lst = new List<user_model>();
            try
            {
                string hostName = Dns.GetHostName();
                ipAddress = Dns.GetHostAddresses(hostName)[0].ToString();

                var pass = Encrypt(model.Password);

                Login_model loginmodel = new Login_model();
                loginmodel.user_id = model.UserName;
                loginmodel.password = pass;
                loginmodel.ip = ipAddress;
                loginmodel.msg = "";
                loginmodel.ip_address = "";
                loginmodel.datasource = "";
                loginmodel.user_code = "";
                loginmodel.user_name = "";
                loginmodel.oldpassword = "";
                string post_data1 = _commonController.GetApiResult(JsonConvert.SerializeObject(loginmodel), "Loginvalidation");
                string d2 = JsonConvert.DeserializeObject<string>(post_data1);
                result = JsonConvert.DeserializeObject<DataTable>(d2);
                for (int i = 0; i < result.Rows.Count; i++)
                {
                    user_model objcat = new user_model();
                    objcat.user_gid = Convert.ToInt32(result.Rows[i]["user_gid"]);
                    objcat.user_name = result.Rows[i]["user_name"].ToString();
                    objcat.passwordexpdate = result.Rows[i]["password_expiry_date"].ToString();
                    objcat.usergroup_gid = Convert.ToInt32(result.Rows[i]["usergroup_code"]);
                    objcat.result = Convert.ToInt32(result.Rows[i]["out_result"]);
                    objcat.msg = result.Rows[i]["out_msg"].ToString();
                    objcat.oldpassworrd = Decrypt(pass);
                    objcat.user_status = result.Rows[i]["user_status"].ToString();
                    objcat_lst.Add(objcat);

                    HttpContext.Session.SetString("usercode", model.UserName);
                    HttpContext.Session.SetString("username", result.Rows[i]["user_name"].ToString());
                    HttpContext.Session.SetString("mindate", result.Rows[i]["min_tran_date"].ToString());
                    HttpContext.Session.SetString("fin_date", result.Rows[i]["fin_start_date"].ToString());
                    HttpContext.Session.SetString("user_code", result.Rows[i]["user_gid"].ToString());
                    HttpContext.Session.SetString("usergroup_code", result.Rows[i]["usergroup_code"].ToString());
                    HttpContext.Session.SetString("userrole", "ADMIN");

                }


            }
            catch (Exception ex)
            {
                string control = this.RouteData.Values["controller"].ToString();
                _logger.LogError(ex, $"An error occurred in {control}");
            }

            return JsonConvert.SerializeObject(objcat_lst);
        }


        private string Encrypt(string clearText)
        {
            try
            {
                string EncryptionKey = "MAKV2SPBNI99212";
                byte[] clearBytes = Encoding.Unicode.GetBytes(clearText);
                using (Aes encryptor = Aes.Create())
                {
                    Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                    encryptor.Key = pdb.GetBytes(32);
                    encryptor.IV = pdb.GetBytes(16);
                    using (MemoryStream ms = new MemoryStream())
                    {
                        using (CryptoStream cs = new CryptoStream(ms, encryptor.CreateEncryptor(), CryptoStreamMode.Write))
                        {
                            cs.Write(clearBytes, 0, clearBytes.Length);
                            cs.Close();
                        }
                        clearText = Convert.ToBase64String(ms.ToArray());
                    }
                }
            }
            catch (Exception e)
            {
                return e.Message;
            }
            return clearText;
        }

        private string Decrypt(string cipherText)
        {
            try
            {
                string EncryptionKey = "MAKV2SPBNI99212";
                byte[] cipherBytes = Convert.FromBase64String(cipherText);
                using (Aes encryptor = Aes.Create())
                {
                    Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                    encryptor.Key = pdb.GetBytes(32);
                    encryptor.IV = pdb.GetBytes(16);
                    using (MemoryStream ms = new MemoryStream())
                    {
                        using (CryptoStream cs = new CryptoStream(ms, encryptor.CreateDecryptor(), CryptoStreamMode.Write))
                        {
                            cs.Write(cipherBytes, 0, cipherBytes.Length);
                            cs.Close();
                        }
                        cipherText = Encoding.Unicode.GetString(ms.ToArray());
                    }
                }
            }
            catch (Exception e)
            {
                return e.Message;
            }
            return cipherText;
        }

        //public ActionResult Forgot_pass(string UserName)
        //{
        //    string message = "";
        //    try
        //    {
        //        string hostName = Dns.GetHostName(); // Retrive the Name of HOST 
        //        ipAddress = Dns.GetHostByName(hostName).AddressList[0].ToString();
        //        List<user_model> objcat_lst = new List<user_model>();
        //        DataTable result = new DataTable();

        //        Login_model Forgot_pass = new Login_model();
        //        Forgot_pass.user_id = UserName;
        //        Forgot_pass.ip = ipAddress;

        //        using (var client = new HttpClient())
        //        {

        //            //string post_data = _commonController.getApiResult(JsonConvert.SerializeObject(Forgot_pass), "forgotpassword");
        //            //result = (DataTable)JsonConvert.DeserializeObject(post_data, result.GetType());
        //            for (int i = 0; i < result.Rows.Count; i++)
        //            {
        //                user_model objcat = new user_model();
        //                objcat.user_emailid = result.Rows[i]["user_emailid"].ToString();
        //                var password = result.Rows[i]["user_password"].ToString();
        //                objcat.oldpassworrd = Decrypt(password);
        //                objcat_lst.Add(objcat);
        //                objcat.FromEmailId = System.Configuration.ConfigurationManager.AppSettings["FromEmailId"];
        //                objcat.Password = System.Configuration.ConfigurationManager.AppSettings["Password"];
        //                objcat.SMTPPort = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["SMTPPort"]);
        //                objcat.Host = System.Configuration.ConfigurationManager.AppSettings["Host"];

        //                if (objcat.user_emailid != "")
        //                {
        //                    var sub = "Password";
        //                    var body = objcat.oldpassworrd;
        //                    var smtp = new SmtpClient
        //                    {
        //                        Host = objcat.Host,
        //                        Port = objcat.SMTPPort,
        //                        EnableSsl = true,
        //                        DeliveryMethod = SmtpDeliveryMethod.Network,
        //                        UseDefaultCredentials = false,
        //                        Credentials = new NetworkCredential(objcat.FromEmailId, objcat.Password)
        //                    };
        //                    using (var mess = new MailMessage(objcat.FromEmailId, objcat.user_emailid)
        //                    {
        //                        Subject = sub,
        //                        Body = body
        //                    })
        //                    {
        //                        smtp.Send(mess);
        //                        message = "Mail Sended Sucessfully";
        //                    }
        //                }
        //                else
        //                {
        //                    message = "failed";
        //                }

ReconWeb/Views/Login/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Recon</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <!-- Font Awesome -->
    <link href="~/Content/css/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link href="~/Content/css/bower_components/Ionicons/css/ionicons.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/Content/css/dist/css/AdminLTE.min.css" rel="stylesheet" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
           folder instead of downloading all of them to reduce the load. -->
    <link href="~/Content/css/dist/css/skins/_all-skins.min.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="dist/css/skins/_all-skins.min.css">*@
    <!-- Morris chart -->
    <link href="~/Content/css/bower_components/morris.js/morris.css" rel="stylesheet" />
    <!-- jvectormap -->
    <link href="~/Content/css/bower_components/jvectormap/jquery-jvectormap.css" rel="stylesheet" />
    <!-- Date Picker -->
    <link href="~/Content/css/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <!-- Daterange picker -->
    <link href="~/Content/css/bower_components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="~/Content/css/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" />
    @*<link href="~/Content/css/dist/css/dms.css" rel="stylesheet" />*@
    <link href="~/Content/css/dist/css/dms.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <style>
        .modal {
            padding-right: 650px !important;
        }
    </style>
    <script src="~/Content/css/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Content/css/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-confirm.min.js"></script>
    <link href="~/Content/css/jquery-confirm.min.css" rel="stylesheet" />
</head>
<body style="        background: url('../../Content/images/login_page.jpg') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: 100%;">
    <div class="container">
        <div class="row" style="margin-top:200px;">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6" style="margin-top:40px;">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                @*<img class="img-responsive" src="~/Content/css/dist/images/impact.jpg" style="border-radius:60px;box-shadow: 0 4px 55px 0 rgba(0, 0, 0, 0.2), 0 6px 27px 0 rgba(0, 0, 0, 0.19);" />*@
            </div>
            <div class="col-sm-4 login-box-body">
                <h3>Login</h3>
                <form action="" class="form-horizontal" method="post" style="height:100%">
                    <div class="form-group has-feedback">
                        <input type="text" class="form-control" name="txtusername" maxlength="50" id="txtusername" placeholder="User Name">
                        <span class="fa fa-user form-control-feedback"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <input type="password" class="form-control" name="txtpwd" maxlength="50" id="txtpwd" placeholder="Password">
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                        @*@Html.ValidationMessageFor(m => m.Password)*@
                        @*<span class="fa fa-eye logineye" onmousedown="mouseoverPass() ;" onmouseup="mouseoutPass();"></span>*@
                    </div>
                    <div class="errormessage" style="color:blue">
                    </div>
                    <div class="row" style="margin-bottom: -37px;">
                        <div class="col-sm-6">
                            <a href="~/Login/ForgetPassword" style="color:#000;margin-left: -11px;" onclick="ForgotPassword()">Forgot Password ?</a><br>
                            <div class="form-group text-center">
                                <span class="Success_show" style="color: white"></span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <button type="button" id="btnsubmit" style="width:100%" onclick=" validation()" class="btn btn-primary btn-block btn-flat">&nbsp;Sign In</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
<script type="text/javascript">
    $(document).ready(function () {
        debugger;
        gettoken();
    });
    function validation() {
        debugger;
        var msg = "";
        if ($("#txtusername").val() != "") {

        }
        else {
            msg += "Please Enter User Name";
        }
        if (msg == "") {
            // window.location.href = "../Dashboard/Dashboard";
            loginvalidation()
        } else {
            $.dialog({
                title: 'Impact',
                content: msg,
                type: 'green',
            });
        }
        return msg;
    }

    function loginvalidation() {
        debugger;
        var UserName = $("#txtusername").val();
        var Password = $("#txtpwd").val();

        //if (UserName == "" || Password == "" || UserName == undefined || UserName == undefined) {
        //     //UserName = "sundar";
        //    //Password = "vino@123";
        //    $.alert({
        //        icon: 'fa fa-warning',
        //        title: 'Impact',
        //        content:"Invalid credentials",
        //        type: 'red',
        //        animationSpeed: 700,
        //    });
        //    return;
        //}


        $.ajax({
            type: "POST",
            //data: '{UserName: "' + UserName + '",Password: "' + Password + '"}',
            url: '@Url.Action("Login_validation", "Login")',
            data: JSON.stringify({
                UserName: UserName,
                Password: Password
            }),
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                debugger;
                    var response = JSON.parse(data);
                if (response[0].user_status == 'N' && response[0].msg !== "Login success !") {
                    var id = response[0].user_gid;
                    location.href = "@Url.Action("", "Login/ChangePassword")?Id=" + id
                }
                else {
                    if (response[0].msg == "Login success !") {
                        window.location.href = '@Url.Action("Index", "Home")';

                    }
                    else {
                        $.dialog({
                            title: 'Impact',
                            content: response[0].msg,
                            type: 'green',
                        });
                    }
                }
            },
            error: function (er) {
            }
        });


    };
    function ForgotPassword() {

    @*var url = '@Url.Action("ForgetPassword", "login")'
            window.location.href = url;*@
                //window.location.href = '../login/ForgetPassword';
            }
    function gettoken() {
        debugger;
        $.ajax({
            type: "GET",
            contentType: "application/json; charset=utf-8",
            async: false,
            url: '@Url.Action("getToken", "Common")',
            data: {},
            success: function (response) {

            }, error: function (data) {

            }
        });
    }
</script>